name: Deploy to EC2

on:
  push:
    branches:
      - main  # Podesi na granu koju koristiš za proizvodnju

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout koda iz GitHub repozitorijuma
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Postavljanje SSH pristupa na EC2 instancu
      - name: Set up SSH for EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}             # IP adresa tvoje EC2 instance
          username: ubuntu                        # Korisničko ime za pristup EC2 (obično ubuntu ili ec2-user)
          key: ${{ secrets.EC2_SSH_KEY }}         # SSH ključ sa kojeg GitHub može da pristupi tvojoj EC2 instanci
          script: |
            cd ~/www-infobit/www-infobit
            git pull origin main
            cp -r ~/www-infobit/www-infobit/* /usr/share/nginx/html/  # Kopiranje statičkih fajlova
            docker-compose down
            docker-compose up -d  # Restartovanje nginx-a ako je potrebno
