name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js for React/Vite build
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          ls -la dist

      # Step 4: Copy dist folder to EC2
      - name: Copy dist folder to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/home/ubuntu/"

      # Step 5: SSH into EC2 and deploy build
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /home/ubuntu/dist/* /usr/share/nginx/html/

            cd ~/www-infobit
            docker-compose down
            docker-compose up -d
